server:
  port: 8080

spring:
  application:
    name: house-management
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/house
    username: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

